// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: BulkAPI.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BulkAPIRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BulkAPIRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BulkAPIRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BulkAPIRequestMultiError,
// or nil if none found.
func (m *BulkAPIRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BulkAPIRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMovie() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BulkAPIRequestValidationError{
						field:  fmt.Sprintf("Movie[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BulkAPIRequestValidationError{
						field:  fmt.Sprintf("Movie[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BulkAPIRequestValidationError{
					field:  fmt.Sprintf("Movie[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BulkAPIRequestMultiError(errors)
	}

	return nil
}

// BulkAPIRequestMultiError is an error wrapping multiple validation errors
// returned by BulkAPIRequest.ValidateAll() if the designated constraints
// aren't met.
type BulkAPIRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BulkAPIRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BulkAPIRequestMultiError) AllErrors() []error { return m }

// BulkAPIRequestValidationError is the validation error returned by
// BulkAPIRequest.Validate if the designated constraints aren't met.
type BulkAPIRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BulkAPIRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BulkAPIRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BulkAPIRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BulkAPIRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BulkAPIRequestValidationError) ErrorName() string { return "BulkAPIRequestValidationError" }

// Error satisfies the builtin error interface
func (e BulkAPIRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBulkAPIRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BulkAPIRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BulkAPIRequestValidationError{}

// Validate checks the field values on BulkAPIResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BulkAPIResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BulkAPIResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BulkAPIResponseMultiError, or nil if none found.
func (m *BulkAPIResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BulkAPIResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return BulkAPIResponseMultiError(errors)
	}

	return nil
}

// BulkAPIResponseMultiError is an error wrapping multiple validation errors
// returned by BulkAPIResponse.ValidateAll() if the designated constraints
// aren't met.
type BulkAPIResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BulkAPIResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BulkAPIResponseMultiError) AllErrors() []error { return m }

// BulkAPIResponseValidationError is the validation error returned by
// BulkAPIResponse.Validate if the designated constraints aren't met.
type BulkAPIResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BulkAPIResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BulkAPIResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BulkAPIResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BulkAPIResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BulkAPIResponseValidationError) ErrorName() string { return "BulkAPIResponseValidationError" }

// Error satisfies the builtin error interface
func (e BulkAPIResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBulkAPIResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BulkAPIResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BulkAPIResponseValidationError{}
