// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: CreateMoviePostgres.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateMoviePostgresRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateMoviePostgresRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMoviePostgresRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMoviePostgresRequestMultiError, or nil if none found.
func (m *CreateMoviePostgresRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMoviePostgresRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMovie() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateMoviePostgresRequestValidationError{
						field:  fmt.Sprintf("Movie[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateMoviePostgresRequestValidationError{
						field:  fmt.Sprintf("Movie[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateMoviePostgresRequestValidationError{
					field:  fmt.Sprintf("Movie[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateMoviePostgresRequestMultiError(errors)
	}

	return nil
}

// CreateMoviePostgresRequestMultiError is an error wrapping multiple
// validation errors returned by CreateMoviePostgresRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateMoviePostgresRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMoviePostgresRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMoviePostgresRequestMultiError) AllErrors() []error { return m }

// CreateMoviePostgresRequestValidationError is the validation error returned
// by CreateMoviePostgresRequest.Validate if the designated constraints aren't met.
type CreateMoviePostgresRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMoviePostgresRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMoviePostgresRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMoviePostgresRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMoviePostgresRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMoviePostgresRequestValidationError) ErrorName() string {
	return "CreateMoviePostgresRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMoviePostgresRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMoviePostgresRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMoviePostgresRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMoviePostgresRequestValidationError{}

// Validate checks the field values on CreateMoviePostgresResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateMoviePostgresResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateMoviePostgresResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateMoviePostgresResponseMultiError, or nil if none found.
func (m *CreateMoviePostgresResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateMoviePostgresResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateMoviePostgresResponseMultiError(errors)
	}

	return nil
}

// CreateMoviePostgresResponseMultiError is an error wrapping multiple
// validation errors returned by CreateMoviePostgresResponse.ValidateAll() if
// the designated constraints aren't met.
type CreateMoviePostgresResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateMoviePostgresResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateMoviePostgresResponseMultiError) AllErrors() []error { return m }

// CreateMoviePostgresResponseValidationError is the validation error returned
// by CreateMoviePostgresResponse.Validate if the designated constraints
// aren't met.
type CreateMoviePostgresResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateMoviePostgresResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateMoviePostgresResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateMoviePostgresResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateMoviePostgresResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateMoviePostgresResponseValidationError) ErrorName() string {
	return "CreateMoviePostgresResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateMoviePostgresResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateMoviePostgresResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateMoviePostgresResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateMoviePostgresResponseValidationError{}
