// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: CreateMoviePostgres.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMoviePostgresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movie []*Movie `protobuf:"bytes,1,rep,name=movie,proto3" json:"movie,omitempty"`
}

func (x *CreateMoviePostgresRequest) Reset() {
	*x = CreateMoviePostgresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CreateMoviePostgres_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMoviePostgresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoviePostgresRequest) ProtoMessage() {}

func (x *CreateMoviePostgresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CreateMoviePostgres_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoviePostgresRequest.ProtoReflect.Descriptor instead.
func (*CreateMoviePostgresRequest) Descriptor() ([]byte, []int) {
	return file_CreateMoviePostgres_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMoviePostgresRequest) GetMovie() []*Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type CreateMoviePostgresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateMoviePostgresResponse) Reset() {
	*x = CreateMoviePostgresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CreateMoviePostgres_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMoviePostgresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoviePostgresResponse) ProtoMessage() {}

func (x *CreateMoviePostgresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CreateMoviePostgres_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoviePostgresResponse.ProtoReflect.Descriptor instead.
func (*CreateMoviePostgresResponse) Descriptor() ([]byte, []int) {
	return file_CreateMoviePostgres_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMoviePostgresResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_CreateMoviePostgres_proto protoreflect.FileDescriptor

var file_CreateMoviePostgres_proto_rawDesc = []byte{
	0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x22, 0x35, 0x0a,
	0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x67, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CreateMoviePostgres_proto_rawDescOnce sync.Once
	file_CreateMoviePostgres_proto_rawDescData = file_CreateMoviePostgres_proto_rawDesc
)

func file_CreateMoviePostgres_proto_rawDescGZIP() []byte {
	file_CreateMoviePostgres_proto_rawDescOnce.Do(func() {
		file_CreateMoviePostgres_proto_rawDescData = protoimpl.X.CompressGZIP(file_CreateMoviePostgres_proto_rawDescData)
	})
	return file_CreateMoviePostgres_proto_rawDescData
}

var file_CreateMoviePostgres_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CreateMoviePostgres_proto_goTypes = []interface{}{
	(*CreateMoviePostgresRequest)(nil),  // 0: proxy_proto.CreateMoviePostgresRequest
	(*CreateMoviePostgresResponse)(nil), // 1: proxy_proto.CreateMoviePostgresResponse
	(*Movie)(nil),                       // 2: proxy_proto.Movie
}
var file_CreateMoviePostgres_proto_depIdxs = []int32{
	2, // 0: proxy_proto.CreateMoviePostgresRequest.movie:type_name -> proxy_proto.Movie
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CreateMoviePostgres_proto_init() }
func file_CreateMoviePostgres_proto_init() {
	if File_CreateMoviePostgres_proto != nil {
		return
	}
	file_movie_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CreateMoviePostgres_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMoviePostgresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CreateMoviePostgres_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMoviePostgresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CreateMoviePostgres_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CreateMoviePostgres_proto_goTypes,
		DependencyIndexes: file_CreateMoviePostgres_proto_depIdxs,
		MessageInfos:      file_CreateMoviePostgres_proto_msgTypes,
	}.Build()
	File_CreateMoviePostgres_proto = out.File
	file_CreateMoviePostgres_proto_rawDesc = nil
	file_CreateMoviePostgres_proto_goTypes = nil
	file_CreateMoviePostgres_proto_depIdxs = nil
}
