// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: DeleteMovie.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeleteMovieRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMovieRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMovieRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMovieRequestMultiError, or nil if none found.
func (m *DeleteMovieRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMovieRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MovieId

	// no validation rules for Title

	if len(errors) > 0 {
		return DeleteMovieRequestMultiError(errors)
	}

	return nil
}

// DeleteMovieRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteMovieRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteMovieRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMovieRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMovieRequestMultiError) AllErrors() []error { return m }

// DeleteMovieRequestValidationError is the validation error returned by
// DeleteMovieRequest.Validate if the designated constraints aren't met.
type DeleteMovieRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMovieRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMovieRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMovieRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMovieRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMovieRequestValidationError) ErrorName() string {
	return "DeleteMovieRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMovieRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMovieRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMovieRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMovieRequestValidationError{}

// Validate checks the field values on DeleteMovieResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMovieResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMovieResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMovieResponseMultiError, or nil if none found.
func (m *DeleteMovieResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMovieResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteMovieResponseMultiError(errors)
	}

	return nil
}

// DeleteMovieResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteMovieResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteMovieResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMovieResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMovieResponseMultiError) AllErrors() []error { return m }

// DeleteMovieResponseValidationError is the validation error returned by
// DeleteMovieResponse.Validate if the designated constraints aren't met.
type DeleteMovieResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMovieResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMovieResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMovieResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMovieResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMovieResponseValidationError) ErrorName() string {
	return "DeleteMovieResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMovieResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMovieResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMovieResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMovieResponseValidationError{}
