// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: GetAllMovie.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *GetAllMovieRequest) Reset() {
	*x = GetAllMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetAllMovie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMovieRequest) ProtoMessage() {}

func (x *GetAllMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetAllMovie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMovieRequest.ProtoReflect.Descriptor instead.
func (*GetAllMovieRequest) Descriptor() ([]byte, []int) {
	return file_GetAllMovie_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllMovieRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetAllMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Took     int64      `protobuf:"varint,1,opt,name=took,proto3" json:"took,omitempty"`
	TimedOut bool       `protobuf:"varint,2,opt,name=timed_out,proto3" json:"timed_out,omitempty"`
	XShards  *Shards    `protobuf:"bytes,3,opt,name=_shards,proto3" json:"_shards,omitempty"`
	Hits     *TotalHits `protobuf:"bytes,4,opt,name=hits,proto3" json:"hits,omitempty"`
}

func (x *GetAllMovieResponse) Reset() {
	*x = GetAllMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetAllMovie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMovieResponse) ProtoMessage() {}

func (x *GetAllMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GetAllMovie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMovieResponse.ProtoReflect.Descriptor instead.
func (*GetAllMovieResponse) Descriptor() ([]byte, []int) {
	return file_GetAllMovie_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllMovieResponse) GetTook() int64 {
	if x != nil {
		return x.Took
	}
	return 0
}

func (x *GetAllMovieResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *GetAllMovieResponse) GetXShards() *Shards {
	if x != nil {
		return x.XShards
	}
	return nil
}

func (x *GetAllMovieResponse) GetHits() *TotalHits {
	if x != nil {
		return x.Hits
	}
	return nil
}

var File_GetAllMovie_proto protoreflect.FileDescriptor

var file_GetAllMovie_proto_rawDesc = []byte{
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x13, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x22, 0xa2, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x6f, 0x6f, 0x6b, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x5f,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x73, 0x52, 0x07, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x68, 0x69,
	0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x48, 0x69, 0x74, 0x73,
	0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetAllMovie_proto_rawDescOnce sync.Once
	file_GetAllMovie_proto_rawDescData = file_GetAllMovie_proto_rawDesc
)

func file_GetAllMovie_proto_rawDescGZIP() []byte {
	file_GetAllMovie_proto_rawDescOnce.Do(func() {
		file_GetAllMovie_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetAllMovie_proto_rawDescData)
	})
	return file_GetAllMovie_proto_rawDescData
}

var file_GetAllMovie_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetAllMovie_proto_goTypes = []interface{}{
	(*GetAllMovieRequest)(nil),  // 0: proxy_proto.GetAllMovieRequest
	(*GetAllMovieResponse)(nil), // 1: proxy_proto.GetAllMovieResponse
	(*Shards)(nil),              // 2: proxy_proto.Shards
	(*TotalHits)(nil),           // 3: proxy_proto.TotalHits
}
var file_GetAllMovie_proto_depIdxs = []int32{
	2, // 0: proxy_proto.GetAllMovieResponse._shards:type_name -> proxy_proto.Shards
	3, // 1: proxy_proto.GetAllMovieResponse.hits:type_name -> proxy_proto.TotalHits
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetAllMovie_proto_init() }
func file_GetAllMovie_proto_init() {
	if File_GetAllMovie_proto != nil {
		return
	}
	file_elasticsearch_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetAllMovie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetAllMovie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetAllMovie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetAllMovie_proto_goTypes,
		DependencyIndexes: file_GetAllMovie_proto_depIdxs,
		MessageInfos:      file_GetAllMovie_proto_msgTypes,
	}.Build()
	File_GetAllMovie_proto = out.File
	file_GetAllMovie_proto_rawDesc = nil
	file_GetAllMovie_proto_goTypes = nil
	file_GetAllMovie_proto_depIdxs = nil
}
