// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: GetIndices.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetIndicesRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetIndicesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIndicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIndicesRequestMultiError, or nil if none found.
func (m *GetIndicesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIndicesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetIndicesRequestMultiError(errors)
	}

	return nil
}

// GetIndicesRequestMultiError is an error wrapping multiple validation errors
// returned by GetIndicesRequest.ValidateAll() if the designated constraints
// aren't met.
type GetIndicesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIndicesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIndicesRequestMultiError) AllErrors() []error { return m }

// GetIndicesRequestValidationError is the validation error returned by
// GetIndicesRequest.Validate if the designated constraints aren't met.
type GetIndicesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIndicesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIndicesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIndicesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIndicesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIndicesRequestValidationError) ErrorName() string {
	return "GetIndicesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetIndicesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIndicesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIndicesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIndicesRequestValidationError{}

// Validate checks the field values on GetIndicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIndicesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIndicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIndicesResponseMultiError, or nil if none found.
func (m *GetIndicesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIndicesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIndexInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIndicesResponseValidationError{
					field:  "IndexInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIndicesResponseValidationError{
					field:  "IndexInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIndexInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIndicesResponseValidationError{
				field:  "IndexInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetIndicesResponseMultiError(errors)
	}

	return nil
}

// GetIndicesResponseMultiError is an error wrapping multiple validation errors
// returned by GetIndicesResponse.ValidateAll() if the designated constraints
// aren't met.
type GetIndicesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIndicesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIndicesResponseMultiError) AllErrors() []error { return m }

// GetIndicesResponseValidationError is the validation error returned by
// GetIndicesResponse.Validate if the designated constraints aren't met.
type GetIndicesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIndicesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIndicesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIndicesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIndicesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIndicesResponseValidationError) ErrorName() string {
	return "GetIndicesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetIndicesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIndicesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIndicesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIndicesResponseValidationError{}

// Validate checks the field values on IndexInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IndexInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IndexInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IndexInfoMultiError, or nil
// if none found.
func (m *IndexInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *IndexInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetIndices()))
		i := 0
		for key := range m.GetIndices() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetIndices()[key]
			_ = val

			// no validation rules for Indices[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, IndexInfoValidationError{
							field:  fmt.Sprintf("Indices[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, IndexInfoValidationError{
							field:  fmt.Sprintf("Indices[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return IndexInfoValidationError{
						field:  fmt.Sprintf("Indices[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return IndexInfoMultiError(errors)
	}

	return nil
}

// IndexInfoMultiError is an error wrapping multiple validation errors returned
// by IndexInfo.ValidateAll() if the designated constraints aren't met.
type IndexInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IndexInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IndexInfoMultiError) AllErrors() []error { return m }

// IndexInfoValidationError is the validation error returned by
// IndexInfo.Validate if the designated constraints aren't met.
type IndexInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IndexInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IndexInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IndexInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IndexInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IndexInfoValidationError) ErrorName() string { return "IndexInfoValidationError" }

// Error satisfies the builtin error interface
func (e IndexInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIndexInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IndexInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IndexInfoValidationError{}
