// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: GetMovieByID.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetMovieByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMovieByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMovieByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMovieByIDRequestMultiError, or nil if none found.
func (m *GetMovieByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMovieByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MovieId

	if len(errors) > 0 {
		return GetMovieByIDRequestMultiError(errors)
	}

	return nil
}

// GetMovieByIDRequestMultiError is an error wrapping multiple validation
// errors returned by GetMovieByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetMovieByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMovieByIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMovieByIDRequestMultiError) AllErrors() []error { return m }

// GetMovieByIDRequestValidationError is the validation error returned by
// GetMovieByIDRequest.Validate if the designated constraints aren't met.
type GetMovieByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMovieByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMovieByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMovieByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMovieByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMovieByIDRequestValidationError) ErrorName() string {
	return "GetMovieByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetMovieByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMovieByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMovieByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMovieByIDRequestValidationError{}

// Validate checks the field values on GetMovieByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMovieByIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMovieByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMovieByIDResponseMultiError, or nil if none found.
func (m *GetMovieByIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMovieByIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for XIndex

	// no validation rules for XId

	// no validation rules for XVersion

	// no validation rules for XSeqNo

	// no validation rules for XPrimaryTerm

	// no validation rules for Found

	if all {
		switch v := interface{}(m.GetXSource()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMovieByIDResponseValidationError{
					field:  "XSource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMovieByIDResponseValidationError{
					field:  "XSource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetXSource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMovieByIDResponseValidationError{
				field:  "XSource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMovieByIDResponseMultiError(errors)
	}

	return nil
}

// GetMovieByIDResponseMultiError is an error wrapping multiple validation
// errors returned by GetMovieByIDResponse.ValidateAll() if the designated
// constraints aren't met.
type GetMovieByIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMovieByIDResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMovieByIDResponseMultiError) AllErrors() []error { return m }

// GetMovieByIDResponseValidationError is the validation error returned by
// GetMovieByIDResponse.Validate if the designated constraints aren't met.
type GetMovieByIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMovieByIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMovieByIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMovieByIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMovieByIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMovieByIDResponseValidationError) ErrorName() string {
	return "GetMovieByIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetMovieByIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMovieByIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMovieByIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMovieByIDResponseValidationError{}
