// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: SearchMoviePostgres.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SearchMoviePostgresRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchMoviePostgresRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchMoviePostgresRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchMoviePostgresRequestMultiError, or nil if none found.
func (m *SearchMoviePostgresRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchMoviePostgresRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Query

	if len(errors) > 0 {
		return SearchMoviePostgresRequestMultiError(errors)
	}

	return nil
}

// SearchMoviePostgresRequestMultiError is an error wrapping multiple
// validation errors returned by SearchMoviePostgresRequest.ValidateAll() if
// the designated constraints aren't met.
type SearchMoviePostgresRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchMoviePostgresRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchMoviePostgresRequestMultiError) AllErrors() []error { return m }

// SearchMoviePostgresRequestValidationError is the validation error returned
// by SearchMoviePostgresRequest.Validate if the designated constraints aren't met.
type SearchMoviePostgresRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchMoviePostgresRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchMoviePostgresRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchMoviePostgresRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchMoviePostgresRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchMoviePostgresRequestValidationError) ErrorName() string {
	return "SearchMoviePostgresRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchMoviePostgresRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchMoviePostgresRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchMoviePostgresRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchMoviePostgresRequestValidationError{}

// Validate checks the field values on SearchMoviePostgresResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchMoviePostgresResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchMoviePostgresResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchMoviePostgresResponseMultiError, or nil if none found.
func (m *SearchMoviePostgresResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchMoviePostgresResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetHits()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SearchMoviePostgresResponseValidationError{
					field:  "Hits",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SearchMoviePostgresResponseValidationError{
					field:  "Hits",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHits()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SearchMoviePostgresResponseValidationError{
				field:  "Hits",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SearchMoviePostgresResponseMultiError(errors)
	}

	return nil
}

// SearchMoviePostgresResponseMultiError is an error wrapping multiple
// validation errors returned by SearchMoviePostgresResponse.ValidateAll() if
// the designated constraints aren't met.
type SearchMoviePostgresResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchMoviePostgresResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchMoviePostgresResponseMultiError) AllErrors() []error { return m }

// SearchMoviePostgresResponseValidationError is the validation error returned
// by SearchMoviePostgresResponse.Validate if the designated constraints
// aren't met.
type SearchMoviePostgresResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchMoviePostgresResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchMoviePostgresResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchMoviePostgresResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchMoviePostgresResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchMoviePostgresResponseValidationError) ErrorName() string {
	return "SearchMoviePostgresResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchMoviePostgresResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchMoviePostgresResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchMoviePostgresResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchMoviePostgresResponseValidationError{}
