// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: SearchMovie.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SearchMovieRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchMovieRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchMovieRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchMovieRequestMultiError, or nil if none found.
func (m *SearchMovieRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchMovieRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Query

	// no validation rules for Cache

	// no validation rules for RedisKey

	if len(errors) > 0 {
		return SearchMovieRequestMultiError(errors)
	}

	return nil
}

// SearchMovieRequestMultiError is an error wrapping multiple validation errors
// returned by SearchMovieRequest.ValidateAll() if the designated constraints
// aren't met.
type SearchMovieRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchMovieRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchMovieRequestMultiError) AllErrors() []error { return m }

// SearchMovieRequestValidationError is the validation error returned by
// SearchMovieRequest.Validate if the designated constraints aren't met.
type SearchMovieRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchMovieRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchMovieRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchMovieRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchMovieRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchMovieRequestValidationError) ErrorName() string {
	return "SearchMovieRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SearchMovieRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchMovieRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchMovieRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchMovieRequestValidationError{}

// Validate checks the field values on SearchMovieResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SearchMovieResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SearchMovieResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SearchMovieResponseMultiError, or nil if none found.
func (m *SearchMovieResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SearchMovieResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetHits()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SearchMovieResponseValidationError{
					field:  "Hits",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SearchMovieResponseValidationError{
					field:  "Hits",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHits()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SearchMovieResponseValidationError{
				field:  "Hits",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSuggest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SearchMovieResponseValidationError{
					field:  "Suggest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SearchMovieResponseValidationError{
					field:  "Suggest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSuggest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SearchMovieResponseValidationError{
				field:  "Suggest",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if len(errors) > 0 {
		return SearchMovieResponseMultiError(errors)
	}

	return nil
}

// SearchMovieResponseMultiError is an error wrapping multiple validation
// errors returned by SearchMovieResponse.ValidateAll() if the designated
// constraints aren't met.
type SearchMovieResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SearchMovieResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SearchMovieResponseMultiError) AllErrors() []error { return m }

// SearchMovieResponseValidationError is the validation error returned by
// SearchMovieResponse.Validate if the designated constraints aren't met.
type SearchMovieResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SearchMovieResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SearchMovieResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SearchMovieResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SearchMovieResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SearchMovieResponseValidationError) ErrorName() string {
	return "SearchMovieResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SearchMovieResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSearchMovieResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SearchMovieResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SearchMovieResponseValidationError{}
