// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: SetCache.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SetCacheRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SetCacheRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetCacheRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetCacheRequestMultiError, or nil if none found.
func (m *SetCacheRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetCacheRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	if len(errors) > 0 {
		return SetCacheRequestMultiError(errors)
	}

	return nil
}

// SetCacheRequestMultiError is an error wrapping multiple validation errors
// returned by SetCacheRequest.ValidateAll() if the designated constraints
// aren't met.
type SetCacheRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetCacheRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetCacheRequestMultiError) AllErrors() []error { return m }

// SetCacheRequestValidationError is the validation error returned by
// SetCacheRequest.Validate if the designated constraints aren't met.
type SetCacheRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetCacheRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetCacheRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetCacheRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetCacheRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetCacheRequestValidationError) ErrorName() string { return "SetCacheRequestValidationError" }

// Error satisfies the builtin error interface
func (e SetCacheRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetCacheRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetCacheRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetCacheRequestValidationError{}

// Validate checks the field values on SetCacheResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SetCacheResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetCacheResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetCacheResponseMultiError, or nil if none found.
func (m *SetCacheResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetCacheResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SetCacheResponseMultiError(errors)
	}

	return nil
}

// SetCacheResponseMultiError is an error wrapping multiple validation errors
// returned by SetCacheResponse.ValidateAll() if the designated constraints
// aren't met.
type SetCacheResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetCacheResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetCacheResponseMultiError) AllErrors() []error { return m }

// SetCacheResponseValidationError is the validation error returned by
// SetCacheResponse.Validate if the designated constraints aren't met.
type SetCacheResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetCacheResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetCacheResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetCacheResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetCacheResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetCacheResponseValidationError) ErrorName() string { return "SetCacheResponseValidationError" }

// Error satisfies the builtin error interface
func (e SetCacheResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetCacheResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetCacheResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetCacheResponseValidationError{}
