{
 "title": "Request hits in 1 minute",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Created movies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reverse_proxy_service_movie_create",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request hits in 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(reverse_proxy_service_hits[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Method search metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(reverse_proxy_service_movie_search[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines working",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "avg(go_goroutines{})", "legendFormat": "${metric} (average)" }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "avg(go_memstats_alloc_bytes{})", "legendFormat": "${metric} (average)" }
   ]
  },
  {
   "title": "reverse_proxy_service_hits (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(reverse_proxy_service_hits{})",
     "legendFormat": "${metric} (average)"
    }
   ]
  }
 ]
}