
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green" ]
      retries: 20
      interval: 5s

  kibana:
    image: docker.elastic.co/kibana/kibana:latest
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5601" ]
      retries: 20
      interval: 5s
