
server:
	go run cmd/app/main.go

#docker-up:
#	docker compose -f docker-compose.yaml up --build
#
#docker-down:
#	docker compose -f docker-compose.yaml down


docker-up:
	docker compose -f docker-compose.local.yaml up --build

docker-down:
	docker compose -f docker-compose.local.yaml down